### ISSUE TITLE
Build release with https://jitpack.io/

### ISSUE THREAD

**Issue by Moddus** [pheynix/TimerView#5]
Hi,
this is just a suggestion. You could maybe use jitpack.io to release your lib.
It is very easy to configure for github-Projects.

Greets,
Moddus

**Comment by pheynix** [comment]
I add your fork version to jitpack.io,but it's didn't work in my android studio.
Then I try the example that provide by jitpack.io,it's didn't work either!
Can you compile them in your android studio?

Test 1:https://jitpack.io/#Moddus/TimerView/96cbc38711
Test 2:https://github.com/jitpack/jitpack.io

example from test 2:

 repositories { 
        jcenter()
        maven { url "https://jitpack.io" }
   }
   dependencies {
         compile 'com.github.jitpack:gradle-simple:1.0'
   }

**Comment by jitpack-io** [comment]
Hi guys,

it would work if the project was converted from an application to an Android library. 
Test 2 does work in general:)
