### ISSUE TITLE
regarding disabling hardware acceleration

### ISSUE THREAD

**Issue by rajasharan** [pheynix/TimerView#7]
I've heard there is a way to opt out of hardware acceleration at individual view level by forcing the software layer. I was wondering if that is possible for this project.

Cheers

**Comment by pheynix** [comment]
Yes,you can disable hardware acceleration at any level you want.
Simply add  `android:layerType="software"` to .xml file;
Demo: https://github.com/pheynix/TimerView/blob/master/app/src/main/res/layout/activity_main.xml
Doc: http://developer.android.com/guide/topics/graphics/hardware-accel.html

**Comment by rajasharan** [comment]
got it :+1:
